<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;
    protected $fillable = [
        'course_name',  
        'class', 
        'subject',
        'description',
        'keyword',
        'course_aim',
        'section_one',
        'lesson_one',
        'lesson_two',
        'video_one',
        'video_two',
        'video_three',
        'video_four',
        'video_five',
        'video_six',
        'video_seven',
        'video_eight',
        'video_nine',
        'video_ten',
        'video_eleven',
        'video_twelve',
        'video_thirteen',
        'video_fourteen',
        'video_fifteen',
        'video_sixteen',
        'video_seventeen',
        'video_eighteen'
        ,'video_nineteen',
        'video_twenty',
        'video_twenty_one',
        'video_twenty_two',
        'video_twenty_three',
        'video_twenty_four',
        'video_twenty_five',
        'video_twenty_six',
        'video_twenty_seven',
        'video_twenty_eight',
        'video_twenty_nine',
        'video_thirty',
        'video_thirty_one',
        'video_thirty_two',
        'video_thirty_three',
        'video_thirty_four',
        'video_thirty_five',
        'lesson_three',
        'lesson_four',
        'lesson_five',
        'section_two',
        'seven_two',
        'lesson_six',
        'lesson_seven',
        'lesson_eight',
        'lesson_nine',
        'lesson_ten',
        'section_three',
        'lesson_eleven',
        'lesson_twelve',
        'lesson_thirtheen',
        'lesson_fourtheen',
        'lesson_fiftheen',
        'section_four',
        'lesson_sixtheen',
        'lesson_seventheen',
        'lesson_eightheen',
        'lesson_ninetheen',
        'lesson_twenty',
        'section_five',
        'lesson_twenty_one',
        'lesson_twenty_two',
        'lesson_twenty_three',
        'lesson_twenty_four',
        'lesson_twenty_five',
        'section_six',
        'lesson_twenty_six',
        'lesson_twenty_seven',
        'lesson_twenty_eight',
        'lesson_twenty_nine',
        'lesson_thirty',
        'section_seven',
        'lesson_thirty_one',
        'lesson_thirty_two',
        'lesson_thirty_three',
        'lesson_thirty_four',
        'lesson_thirty_five',
        'course_price', 
        'discounted_price',
        'teacher_name', 

                            ];

}
